2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_setup.py:_flush():75] Loading settings from /home/ludvik/.config/wandb/settings
2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_setup.py:_flush():75] Loading settings from /home/ludvik/Desktop/rs_sb3/wandb/settings
2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'run_multiple_tests.py', 'program': 'run_multiple_tests.py'}
2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_init.py:_log_setup():405] Logging user logs to /home/ludvik/Desktop/rs_sb3/wandb/run-20220324_170949-2vgvrj4r/logs/debug.log
2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_init.py:_log_setup():406] Logging internal logs to /home/ludvik/Desktop/rs_sb3/wandb/run-20220324_170949-2vgvrj4r/logs/debug-internal.log
2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_init.py:init():439] calling init triggers
2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-24 17:09:49,755 INFO    MainThread:186133 [wandb_init.py:init():492] starting backend
2022-03-24 17:09:49,755 INFO    MainThread:186133 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-24 17:09:49,766 INFO    MainThread:186133 [backend.py:ensure_launched():219] starting backend process...
2022-03-24 17:09:49,772 INFO    MainThread:186133 [backend.py:ensure_launched():224] started backend process with pid: 186186
2022-03-24 17:09:49,773 INFO    MainThread:186133 [wandb_init.py:init():501] backend started and connected
2022-03-24 17:09:49,779 INFO    MainThread:186133 [wandb_init.py:init():565] updated telemetry
2022-03-24 17:09:49,795 INFO    MainThread:186133 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-24 17:09:50,806 INFO    MainThread:186133 [wandb_run.py:_on_init():1759] communicating current version
2022-03-24 17:09:50,995 INFO    MainThread:186133 [wandb_run.py:_on_init():1763] got version response 
2022-03-24 17:09:50,995 INFO    MainThread:186133 [wandb_init.py:init():625] starting run threads in backend
2022-03-24 17:09:54,140 INFO    MainThread:186133 [wandb_run.py:_console_start():1733] atexit reg
2022-03-24 17:09:54,141 INFO    MainThread:186133 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-03-24 17:09:54,141 INFO    MainThread:186133 [wandb_run.py:_redirect():1611] Redirecting console.
2022-03-24 17:09:54,143 INFO    MainThread:186133 [wandb_run.py:_redirect():1667] Redirects installed.
2022-03-24 17:09:54,143 INFO    MainThread:186133 [wandb_init.py:init():664] run started, returning control to user process
2022-03-24 17:09:58,205 INFO    MainThread:186133 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-03-24 17:09:58,208 INFO    MainThread:186133 [wandb_run.py:_restore():1674] restore
2022-03-24 17:10:00,701 INFO    MainThread:186133 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 788
}

2022-03-24 17:10:01,140 INFO    MainThread:186133 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 788
}

2022-03-24 17:10:01,817 INFO    MainThread:186133 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 18868
}

2022-03-24 17:10:01,919 INFO    MainThread:186133 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 18868
}

2022-03-24 17:10:02,021 INFO    MainThread:186133 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 18868
}

2022-03-24 17:10:02,123 INFO    MainThread:186133 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 18868
}

2022-03-24 17:10:02,225 INFO    MainThread:186133 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 788
  total_bytes: 18868
}

